FROM centos:6.10

#curl sets up the correct website for yum -y update
RUN curl https://www.getpagespeed.com/files/centos6-eol.repo --output /etc/yum.repos.d/CentOS-Base.repo; \

    # Install packages
    yum -y update && yum install -y wget gcc gcc-c++ readline-devel perl && yum clean all -y; \

    # Add epel repo
    # epel-release has been archived, new link
    wget https://archives.fedoraproject.org/pub/archive/epel/6/x86_64/epel-release-6-8.noarch.rpm; \
    rpm -ivh epel-release-6-8.noarch.rpm; \
    rm -rf epel-release-6-8.noarch.rpm; \

    # Install extra packages from epel
    # util-linux-ng is used by cexp
    yum install -y re2c util-linux-ng && yum clean all -y

# Define some common global env vars
## EPICS base version
ENV EPICS_BASE_VERSION *TAG_BASE_VERSION
## Host architecture
ENV EPICS_HOST_ARCH rhel6-x86_64
## Top directory for all EPICS related packages
ENV EPICS_SITE_TOP /usr/local/src/epics
## Top directory for base
ENV BASE_SITE_TOP ${EPICS_SITE_TOP}/base
## Directory of the EPICS base version we are using
ENV EPICS_BASE ${BASE_SITE_TOP}/${EPICS_BASE_VERSION}
## Top directory for modules
ENV EPICS_MODULES ${EPICS_SITE_TOP}/${EPICS_BASE_VERSION}/modules
## Top directory for IOCs
ENV IOC_SITE_TOP ${EPICS_SITE_TOP}/iocTop
## Top directory for packages
ENV PACKAGE_SITE_TOP /usr/local/src/packages
## EPICS CONFIGURATIONS
ENV EPICS_CA_REPEATER_PORT 5065
ENV EPICS_CA_AUTO_ADDR_LIST YES
ENV EPICS_CA_SERVER_PORT 5064
ENV IOC_DATA /data/epics/ioc/data

# Install packages
# (I'm copying the ones from AFS for now instead of recompile...)
WORKDIR ${PACKAGE_SITE_TOP}
COPY temp_files/packages ./

# Install EPICS base
RUN mkdir -p ${BASE_SITE_TOP}; \
    mkdir -p ${IOC_DATA}
WORKDIR ${BASE_SITE_TOP}

COPY temp_files/base .
WORKDIR ${EPICS_BASE_VERSION}
# Build only for the host architecture
RUN sed -i -e 's/^CROSS_COMPILER_TARGET_ARCHS=.*/CROSS_COMPILER_TARGET_ARCHS=/g' configure/CONFIG_SITE; \
    sed -i -e 's/^CROSS_COMPILER_TARGET_ARCHS +=.*/CROSS_COMPILER_TARGET_ARCHS +=/g' configure/CONFIG_SITE; \
    make

ENV PATH ${PATH}:${EPICS_BASE}/bin/${EPICS_HOST_ARCH}
ENV LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${EPICS_BASE}/lib/${EPICS_HOST_ARCH}

# Install EPICS modules
WORKDIR ${EPICS_MODULES}
ADD temp_files/modules/RELEASE_SITE .
